### ISSUE TITLE
ModuleNotFoundError: No module named 'model.roi_align._ext.roi_align._roi_align'

### ISSUE THREAD

**Issue by YuanZhichao** [deneb2016/WSDDN.pytorch#1]
How to run the project? I tryed to run train.py derectly and met the problem:

Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from model.wsddn_vgg16 import WSDDN_VGG16
  File "/home/yzc/Projects/WSDDN.pytorch/model/wsddn_vgg16.py", line 10, in <module>
    from model.roi_align.modules.roi_align import RoIAlignAvg
  File "/home/yzc/Projects/WSDDN.pytorch/model/roi_align/modules/roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction
  File "/home/yzc/Projects/WSDDN.pytorch/model/roi_align/functions/roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "/home/yzc/Projects/WSDDN.pytorch/model/roi_align/_ext/roi_align/__init__.py", line 3, in <module>
    from ._roi_align import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'model.roi_align._ext.roi_align._roi_align'

I'm working on python3.7, pytorch0.4.1. How can I solve the problem?

**Comment by deneb2016** [comment]
Run make.sh to compile roi pooling and roi align.
By the way, I failed to reproduce the original performance shown in the paper.
This pytorch implementation shows 31 mAP on Pascal VOC07 test set.

**Comment by YuanZhichao** [comment]
Thank you! After running make.sh the problem above is solved. 
Now I have another problem. Do I need to prepare for the dataset? I met the following problem:

FileNotFoundError: [Errno 2] No such file or directory: '~/dataset/VOC/proposals/edge_boxes_voc_2007_trainval.mat'

I've changed the 'data_dir' to my own directory. Where can I get the mat file.

**Comment by deneb2016** [comment]
You should download pre-computed EdgeBoxes proposals.
You can find the download link from the original WSDDN [repository](https://github.com/hbilen/WSDDN).

P.S. 
Actually, this code is not ready to open to the public. But I mistakenly made it public.

**Comment by YuanZhichao** [comment]
I see it and thank you! 
I'm a starter at cv and WSDDN. I'm working on my thesis for bachelor's degree. Could I keep in touch with you about the code?
You say that the code is not well prepared. And what is the problem? I'd like to learn it and thank you again!

**Comment by deneb2016** [comment]
Sure, you can ask me any questions about this code.
The problems of this code are listed below,
1. The performance is lower than the original matlab implementation. 
2. The code is not well-structured and there are some useless code...

**Comment by YuanZhichao** [comment]
Hello. It seems that I need a specific caffe pretrained model to start my first time training. Where can I get the pth file? Did you create it by yourself? 
By the way, I failed to download the pre-computed edge-boxes file for testing. Is it available now on the original repository?

**Comment by deneb2016** [comment]
1. You can find the download link of pre-trained caffe model from Faster-RCNN [repository](https://github.com/jwyang/faster-rcnn.pytorch).

2. Hmm.. it seems that edge-boxes file of test split is not available... 
Unfortunately I don't have the file now...

**Comment by YuanZhichao** [comment]
Hello. Thank you for your instruction! I've finished the training process. 
BTY, I found the url on the original repository is wrong and downloaded the mat file successfully.  
Sorry for bothering you again, but while running eval.py, I met this problem:

`Traceback (most recent call last):
  File "eval.py", line 20, in <module>
    from utils.cpu_nms import cpu_nms as nms
ModuleNotFoundError: No module named 'utils.cpu_nms'`

What is the problem? @deneb2016

**Comment by bywang2018** [comment]
Hello. Can you tell me the network parameters(learning rate、alpha and etc) when the mAP is equal to 31%? Thank you！

**Comment by alexshaodong** [comment]
> 1. You can find the download link of pre-trained caffe model from Faster-RCNN [repository](https://github.com/jwyang/faster-rcnn.pytorch).
> 2. Hmm.. it seems that edge-boxes file of test split is not available...
>    Unfortunately I don't have the file now...

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.

**Comment by alexshaodong** [comment]
> How to run the project? I tryed to run train.py derectly and met the problem:
> 
> Traceback (most recent call last):
> File "train.py", line 15, in 
> from model.wsddn_vgg16 import WSDDN_VGG16
> File "/home/yzc/Projects/WSDDN.pytorch/model/wsddn_vgg16.py", line 10, in 
> from model.roi_align.modules.roi_align import RoIAlignAvg
> File "/home/yzc/Projects/WSDDN.pytorch/model/roi_align/modules/roi_align.py", line 3, in 
> from ..functions.roi_align import RoIAlignFunction
> File "/home/yzc/Projects/WSDDN.pytorch/model/roi_align/functions/roi_align.py", line 3, in 
> from .._ext import roi_align
> File "/home/yzc/Projects/WSDDN.pytorch/model/roi_align/_ext/roi_align/**init**.py", line 3, in 
> from ._roi_align import lib as _lib, ffi as _ffi
> ModuleNotFoundError: No module named 'model.roi_align._ext.roi_align._roi_align'
> 
> I'm working on python3.7, pytorch0.4.1. How can I solve the problem?

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.

**Comment by alexshaodong** [comment]
> Hello. Can you tell me the network parameters(learning rate、alpha and etc) when the mAP is equal to 31%? Thank you！

Hello! If I want to train with my own data, how to generate edgeboxes mat files, similar to EdgeBoxes VOC2007trainval. mat and EdgeBoxes VOC2007test. mat files.

**Comment by alexshaodong** [comment]
> 
> 
> Hello. Thank you for your instruction! I've finished the training process.
> BTY, I found the url on the original repository is wrong and downloaded the mat file successfully.
> Sorry for bothering you again, but while running eval.py, I met this problem:
> 
> `Traceback (most recent call last): File "eval.py", line 20, in <module> from utils.cpu_nms import cpu_nms as nms ModuleNotFoundError: No module named 'utils.cpu_nms'`
> 
> What is the problem? @deneb2016

Hello! I would like to ask how to train my own wsddn model. Because I am a novice, without reading me, I really don't know how to train. I want to ask you to teach me. Thank you!

**Comment by jiajunhua** [comment]
Hello, when I run the projct, some probelm appears,how to fix it,thanks in advance.
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from misc import utils, eval_utils, AttModel
  File "D:\PycharmProjects\NeuralBabyTalk-master\misc\AttModel.py", line 10, in <module>
    from misc.model import AttModel
  File "D:\PycharmProjects\NeuralBabyTalk-master\misc\model.py", line 14, in <module>
    from pooling.roi_align.modules.roi_align import RoIAlignAvg
  File "D:\PycharmProjects\NeuralBabyTalk-master\pooling\roi_align\modules\roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction
  File "D:\PycharmProjects\NeuralBabyTalk-master\pooling\roi_align\functions\roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "D:\PycharmProjects\NeuralBabyTalk-master\pooling\roi_align\_ext\roi_align\__init__.py", line 5, in <module>
    from ._roi_align import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'pooling.roi_align._ext.roi_align._roi_align'
